name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Hello world
        run: echo "Hello world GitHub Actions"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Validate lock file presence
        run: |
          if [ ! -f package-lock.json ]; then
            echo "Error: package-lock.json is missing. Run 'npm install' locally to generate it."
            exit 1
          fi

      - name: Install dependencies
        run: npm ci

      - name: Run build (if present)
        run: npm run build --if-present

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PWD }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: bovypt/node-docker:latest andrenextu/node-docker:${{ github.sha }}
